"""Public execution-layer contracts."""

from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from .app import (
        OBSERVE_ONLY_POLICY_ID,
        AppExitCode,
        PaperAppError,
        PaperApplication,
        PaperAppResult,
        RecoveredSnapshot,
        ReplayRequest,
        assemble_observation_replay,
        inspect_events,
        monitor_recovered,
        monitoring_result_to_dict,
        recover_snapshot,
        run_foreground_replay,
    )
    from .broker import BrokerOrderRejected
    from .broker_capabilities import (
        BrokerCapability,
        BrokerCapabilityProvider,
        BrokerCompatibility,
        BrokerDescriptor,
        BrokerEnvironment,
        inspect_broker_capabilities,
        required_capabilities_for_order,
    )
    from .durable_event_store import SQLiteEventStore, StoredCheckpoint
    from .event_ledger import (
        AuditComponent,
        AuditEvent,
        AuditEventType,
        AuditLedgerError,
        EventCorrelation,
        EventLedger,
    )
    from .monitoring import (
        AccountMonitoringView,
        AuditEventMonitoringView,
        BrokerMonitoringView,
        MonitoringResult,
        MonitoringSnapshot,
        MonitoringSource,
        OrderMonitoringView,
        PositionMonitoringView,
        ProviderMonitoringView,
        RecoveryMonitoringView,
        RiskMonitoringView,
        RuntimeMonitoringView,
        monitoring_to_dict,
        project_audit_events,
    )
    from .oanda_demo_broker import (
        OANDA_PRACTICE_AUTHORITY,
        OandaDemoBroker,
        OandaHttpTransport,
        OandaResponse,
        OandaTransport,
    )
    from .order_manager import (
        ExecutionIntent,
        ExecutionResult,
        ExecutionResultKind,
        OrderManager,
        OrderRecord,
    )
    from .paper_broker import CloseReason, OrderCorrelation, PaperBroker, PositionClose
    from .paper_session import (
        CycleKind,
        ExecutionPolicy,
        HistoricalBarReplay,
        MarketContext,
        PaperCycleResult,
        PaperTradingSession,
    )
    from .reconciliation import (
        ReconciliationEngine,
        ReconciliationPlan,
        ReconciliationResult,
        ReconciliationStatus,
    )
    from .recovery import (
        RecoveryResult,
        RecoveryState,
        UnsafeCheckpointError,
        create_checkpoint,
        create_reconciliation_checkpoint,
        recover,
        validate_reconciliation_safe_point,
    )
    from .runtime_control import (
        RuntimeController,
        RuntimeControlReason,
        RuntimeControlResult,
        RuntimeState,
        RuntimeStatus,
    )

__all__ = [
    "OBSERVE_ONLY_POLICY_ID",
    "AppExitCode",
    "PaperApplication",
    "PaperAppError",
    "PaperAppResult",
    "RecoveredSnapshot",
    "ReplayRequest",
    "assemble_observation_replay",
    "inspect_events",
    "monitor_recovered",
    "monitoring_result_to_dict",
    "recover_snapshot",
    "run_foreground_replay",
    "AuditComponent",
    "BrokerOrderRejected",
    "BrokerCapability",
    "BrokerCapabilityProvider",
    "BrokerCompatibility",
    "BrokerDescriptor",
    "BrokerEnvironment",
    "AuditEvent",
    "AuditEventType",
    "AuditLedgerError",
    "EventCorrelation",
    "EventLedger",
    "SQLiteEventStore",
    "StoredCheckpoint",
    "RecoveryResult",
    "RecoveryState",
    "UnsafeCheckpointError",
    "create_checkpoint",
    "create_reconciliation_checkpoint",
    "recover",
    "validate_reconciliation_safe_point",
    "ReconciliationEngine",
    "ReconciliationPlan",
    "ReconciliationResult",
    "ReconciliationStatus",
    "ExecutionIntent",
    "ExecutionResult",
    "ExecutionResultKind",
    "OrderManager",
    "OrderRecord",
    "OANDA_PRACTICE_AUTHORITY",
    "OandaDemoBroker",
    "OandaHttpTransport",
    "OandaResponse",
    "OandaTransport",
    "AccountMonitoringView",
    "AuditEventMonitoringView",
    "BrokerMonitoringView",
    "MonitoringResult",
    "MonitoringSnapshot",
    "MonitoringSource",
    "OrderMonitoringView",
    "PositionMonitoringView",
    "ProviderMonitoringView",
    "RecoveryMonitoringView",
    "RiskMonitoringView",
    "RuntimeMonitoringView",
    "monitoring_to_dict",
    "project_audit_events",
    "OrderCorrelation",
    "PaperBroker",
    "CloseReason",
    "PositionClose",
    "CycleKind",
    "ExecutionPolicy",
    "HistoricalBarReplay",
    "MarketContext",
    "PaperCycleResult",
    "PaperTradingSession",
    "RuntimeControlReason",
    "RuntimeControlResult",
    "RuntimeController",
    "RuntimeState",
    "RuntimeStatus",
    "inspect_broker_capabilities",
    "required_capabilities_for_order",
]


def __getattr__(name: str) -> Any:
    if name in __all__:
        from . import (
            app,
            broker,
            broker_capabilities,
            durable_event_store,
            event_ledger,
            monitoring,
            oanda_demo_broker,
            order_manager,
            paper_broker,
            paper_session,
            reconciliation,
            recovery,
            runtime_control,
        )

        for module in (
            app,
            broker,
            broker_capabilities,
            durable_event_store,
            event_ledger,
            monitoring,
            order_manager,
            oanda_demo_broker,
            paper_broker,
            paper_session,
            reconciliation,
            recovery,
            runtime_control,
        ):
            if hasattr(module, name):
                return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
